CREATE TABLE `Site` (
  `id` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `slug` VARCHAR(191) NOT NULL,
  `primaryDomain` VARCHAR(191) NOT NULL,
  `secondaryDomains` JSON NULL,
  `siteUrl` VARCHAR(191) NOT NULL,
  `locale` VARCHAR(191) NOT NULL DEFAULT 'ro',
  `siteType` VARCHAR(191) NOT NULL DEFAULT 'publisher',
  `themeKey` VARCHAR(191) NOT NULL DEFAULT 'candvisam',
  `templatePack` VARCHAR(191) NOT NULL DEFAULT 'candvisam',
  `logoText` VARCHAR(191) NULL,
  `tagline` TEXT NULL,
  `description` TEXT NULL,
  `searchPath` VARCHAR(191) NOT NULL DEFAULT '/cauta',
  `dictionaryPath` VARCHAR(191) NULL DEFAULT '/dictionar',
  `footerLinks` JSON NULL,
  `featureFlags` JSON NULL,
  `isActive` BOOLEAN NOT NULL DEFAULT true,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `Site_slug_key`(`slug`),
  UNIQUE INDEX `Site_primaryDomain_key`(`primaryDomain`),
  UNIQUE INDEX `Site_siteUrl_key`(`siteUrl`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;