ALTER TABLE `Post`
  ADD COLUMN `pageType` ENUM('CONTENT', 'LANDING', 'HUB', 'SUPPORT') NOT NULL DEFAULT 'CONTENT',
  ADD COLUMN `templateType` ENUM('ARTICLE', 'DREAM', 'SYMBOL', 'HUB', 'GUIDE', 'LANDING') NOT NULL DEFAULT 'ARTICLE',
  ADD COLUMN `verticalType` ENUM('DREAMS', 'SYMBOLS', 'ANGEL_NUMBERS', 'GENERIC') NOT NULL DEFAULT 'DREAMS';
